CUDA_VISIBLE_DEVICES=0 python main_qa.py \
	--mode train \
	--feature_path ./data/visual_feature/ \
	--text_feature_path ./data/text_feature/ \
	--data_path ./data/QA/ \
	--split_path ./data/split/ \
	--checkpoint_path ./experiment \
	--model_type B2A \
	--model_prefix B2A_bert \
	--result_file ./result/{}/{}_{}.json \
	--vid_dim 4096 \
	--hidden_dim 128 \
	--word_dim 300 \
	--max_vid_len 16 \
	--max_qa_len 40 \
	--epoch_num 30 \
	--lr_rate 2e-4 \
	--batch_size 128 \
	--use_bert